GET http://localhost:4444/estados

###

POST http://localhost:4444/estados
Content-Type: application/json

{

    "nome": "Rio de Janeiro",
    "sigla": "RJ"

}

###

PUT http://localhost:4444/estados
Content-Type: application/json

{
    "id": 3,
    "nome": "Rio de Janeiro",
    "sigla": "RJ"

}

###

DELETE http://localhost:4444/estados
Content-Type: application/json

{
    "id": 3
}

###
POST http://localhost:4444/cidades
Content-Type: application/json

{
    "nome" : "Belo Horizonte",
    "estado_id": 1

}